name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main

concurrency:
    group: deploy
    cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            environment: Production
        secrets: inherit

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: Production
        needs: build

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ needs.build.outputs.artifact-name }}
                  path: dist

            - name: Publish to Cloudflare Pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: taco-tapper
                  branch: main
                  directory: dist
